<?xml version="1.0"?>
<package format="3">
  <name>multicamera_pipeline</name>
  <version>0.1.0</version>
  <description>RTSP-only Luxonis camera pipeline for Cavalla forklifts.</description>

  <maintainer email="tony@cavalla.ai">Tony Loehr</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>depthai_ros_driver</exec_depend>
  <exec_depend>depthai_ros_msgs</exec_depend>
  <exec_depend>python3-gi</exec_depend>
  <exec_depend>gir1.2-gst-plugins-base-1.0</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
