[metadata]
name = multicamera_pipeline
version = 0.1.0
author = Tony Loehr
license = Apache-2.0
description = RTSP bridge and launch files for Cavalla forklifts.

[options]
packages = find:
install_requires =
    rclpy
    depthai_ros_msgs
    python-gi

[options.entry_points]
console_scripts =
    oak_rtsp_bridge = multicamera_pipeline.oak_rtsp_bridge:main
